name: ocr_sdk_example
description: A simple Flutter OCR SDK-style example app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera & image picker
  image_picker: ^1.1.2

  # OCR / Text Recognition
  google_mlkit_text_recognition: ^0.14.0

  # ML Kit Barcode Scanning (for QR code)
  google_mlkit_barcode_scanning: ^0.13.0

  # State management & routing
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

